project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "KAXA Space Cambodia"
  search: false
  navbar:
    background: light
    pinned: true
    logo: image/kaxa-logo-white.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: learn/index.qmd
        text: Learn
      - href: blog/index.qmd
        text: Blog
  page-footer:
    left: "KAXA | Cambodia"
    right: "Together, we can reach infinity and beyond!"

format:
  html:
    theme:
      - flatly
    css: theme-space.css
    embed-resources: true
    toc: false

editor: visual

